version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  build: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/node:8.9 # specifically, a docker image with ruby 2.4.1
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls pulls code down from GitHub
      - run: echo "npm installing" # This prints "A first hello" to stdout.
      - run: npm install # a command telling the job to "sleep" for 25 seconds.
      - run: CI=ture npm run build
  test: # This is our second job.
    docker: # it runs inside a docker image, the same as above.
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing stuff" # We run a similar echo command to above.
      - run: npm install
      - run: npm test
  hithere:
    docker: # it runs inside a docker image, the same as above.
      - image: circleci/node:8.9
    steps:
      - checkout:
      - run: echo "hellllllloooooo!"
# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2
  build_test_and_lint: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
      - hithere
      - test:
          requires:
            - hithere
