version: 2 
jobs:
    bobby:
        docker:
            - image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run: echo "A first heelo"
    sally:
        docker:
            - image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run: echo "Double truoble"
    workflows:
        version: 2
        bobby_sally:
            jobs:
                - bobby
                - sally